name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        echo "Compiling the code..."
        echo "Compile complete."

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Lint
      run: |
        echo "Linting code... This will take about 10 seconds."
        sleep 10
        echo "No lint issues found."

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: |
        echo "Deploying application..."
        echo "Application successfully deployed."